### ISSUE TITLE
📝 Create placeholder Navigation component

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#110]
Placeholder Nav component for development accessibility.

Links:

- [x] Signup
- [x] Login
- [x] Dashboard
- [x] Home
- [x] Logout

**Comment by Thenlie** [comment]
Just as a note for people in the future (since my wording is confusing) this is a temporary nav so developers have links to click. This is NOT a loading animation for the nav.

**Comment by Thenlie** [comment]
Closed by #117
