### ISSUE TITLE
🏗 Configure Babel to minimize MUI bundle size

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#139]
> It should be noted that we can use [the babel plugin](https://mui.com/material-ui/guides/minimizing-bundle-size/#option-two-use-a-babel-plugin) to help minimize bundle sizes and use a single line import.

_Originally posted by @jadenrapp in https://github.com/Thenlie/Streamability/pull/138#discussion_r1033008048_
     
Since we already have Babel this should be fairly simple

**Comment by jadenrapp** [comment]
Closed by #238
