### ISSUE TITLE
🐞 App navigates to /dashboard when app goes out of focus

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#155]
To recreate this bug:

Open app and navigate to any page except `/dashboard`, unfocus browser tab and return, you will now be at `/dashboard`

Most likely due to `AppWrapper.tsx` line 52.

**Comment by Thenlie** [comment]
## ✅ Confirmed

Delete line 52 to resolve. Easy win 💪

**Comment by Thenlie** [comment]
Closed by #165
