### ISSUE TITLE
📝 Create ratingHandler utility function

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#158]
Create function for age rating of movies to be displayed in `ShowCard.tsx`, `ShowDetailsScreen.tsx` and any other screens / components in the future.

Currently, our function looks like:
```
const ratingHandler = (arr: MovieDetailsData): JSX.Element | null => {
		for (let i = 0; i < arr.release_dates.results.length; i++) {
			if (arr.release_dates.results[i].iso_3166_1 === 'US') {
				return <p>{arr.release_dates.results[i].release_dates[0].certification}</p>;
			}
		}
		return null;
	};
```

**Comment by Thenlie** [comment]
I think we may want to call this `ageRatingHandler` as we will have a review rating as well.
