### ISSUE TITLE
📝 Create utility formatter function for dates and times

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#160]
This will be used to format movie/show release dates and movie/show runtimes

- [x] Long format `December 12th, 2022`
- [x] Medium format `Dec 12, 2022`
- [x] Short format `12-12-22`

**Comment by Thenlie** [comment]
I think it would be nice to just leverage the normal JS Date object, rather than use something like Moment or Luxon. I think we will have so few date formats that it will not be worth the bloat of another library. Plus, the Date object is actually pretty good these days.

**Comment by Thenlie** [comment]
🧪 Be sure to create unit tests as well!

**Comment by Thenlie** [comment]
Closed by #185
