### ISSUE TITLE
🐞 ShowCard component does not allow adding/removing to queue

### ISSUE THREAD

**Issue by jadenrapp** [Thenlie/Streamability#175]
Bug is originating from line 49 of `ShowCard.tsx`.
https://github.com/Thenlie/Streamability/blob/019a135c5bfa55cdc8a8e0b2ce78cc7321229b59/src/components/ShowCard.tsx#L49
The entire element is linking to the details page, not allowing buttons nested inside to be used.

**Comment by Thenlie** [comment]
I think I can pull this in as part of #114
