### ISSUE TITLE
🐞 ShowDetailsScreen fails to display any content if `US` property is not returned

### ISSUE THREAD

**Issue by jadenrapp** [Thenlie/Streamability#177]
Bug _seems_ to originate here:
https://github.com/Thenlie/Streamability/blob/019a135c5bfa55cdc8a8e0b2ce78cc7321229b59/src/screens/ShowDetailsScreen.tsx#L50-L57

The `US` property is not guaranteed to return on the `results` object and this causes the error when it is not.

You can test this by searching for the following:

- Stranger Things (ID: 182026)
- Your Name (ID: 553301)
- The Invincible Iron Man (ID: 13647)

**Comment by Thenlie** [comment]
# ✅ Confirmed

Currently thinking we should just return a text element saying that there are no streaming providers available in your area.

**Comment by Thenlie** [comment]
Closed by #190 

Nice work @maxh1231 👍
