### ISSUE TITLE
🏗️  Improve search results screen skeleton loader

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#194]
## We may want to wait until #436 is complete before doing this as that could change the look of the loading component.

Use the show card loader to build out a search results screen loader. This ticket will involve a refactor of the show card loading component.

## Resources 🔗 

https://www.npmjs.com/package/react-loading-skeleton

**Comment by maxh1231** [comment]
With skeletons currently displaying during load, improve to match loaded result.

**Comment by Thenlie** [comment]
We may want to wait until #436 is complete before doing this as that could change the look of the loading component.

**Comment by Thenlie** [comment]
Closed by #483
