### ISSUE TITLE
🐞 Certain Movies do not display age rating

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#239]
**Describe the bug**
Certain Movies do not display age rating. The `release_dates` object that is returned does not follow a consistent pattern. Our current `returnRating` function sometimes targets the wrong object. 

**To Reproduce**
1. Search Star Wars
2. First result does not have age rating
3. In `SearchResultsScreen.tsx`, on line 44, console.log `movie`. `age_rating` is an empty string.

**Expected behavior**
An age rating to be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/41771785/210904021-2a4c6a81-e381-43a0-8cf4-985cbb3e4860.png)
For the vast majority of movies, the US certification (age rating), is housed in `release_dates[0]`.

![image](https://user-images.githubusercontent.com/41771785/210904123-91b2e502-903c-46dc-b14d-7ccef5d40bc8.png)
For the movie in question (and most likely others), our function is targeting the '2 week pre-release', which does not have an age rating.

**Comment by Thenlie** [comment]
We might also be able to combine the rating handler functions for movie and tv. Would be worth looking into on this ticket.

**Comment by Thenlie** [comment]
Closed by #292
