### ISSUE TITLE
🧼 Universally decide a proper naming convention for the multiple Types we are using

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#243]
**Is your feature request related to a problem? Please describe.**
As more and more Types are getting defined, many become convoluted and unorganized. 

**Describe the solution you'd like**
Walk through each type and rename them accordingly with each/most of the contributors on this app.

**Comment by Thenlie** [comment]
## Let's discuss this in 1.5.0 planning

**Comment by Thenlie** [comment]
Closed by #253
