### ISSUE TITLE
💡 Determine CSS/component libraries to use

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#42]
## Research CSS Libraries

Determining the tooling for the project early on will be helpful to avoid large roadblocks down the line. As such, it would be worth picking some CSS tooling right away. This will allow front-end developers to know what pre-made components and styles are at their disposal, and what they would need to create from scratch. 

Ideally a single library will be used to keep styling consistent.

**Comment by Thenlie** [comment]
The obvious choices are Tailwind, Bulma, and Bootstrap. MaterialUI also looks like a cool option. 

Using some SCSS would also be really cool!

@Thorulfr if you are interested, feel free to self-assign this issue.

**Comment by Thorulfr** [comment]
I would still vote for Tailwind. Out of the other three, however, Material UI would be the only other one I'm particularly interested in trying. SCSS would be dope too, though tbh we'd be writing very little manual CSS if we're using a framework.

**Comment by Thenlie** [comment]
@Thorulfr A component lib is another thing we probably want to decide from the outset. I'll take a look at MUI, any others you've had your eye on?

**Comment by Thenlie** [comment]
✅ Material UI

**Comment by Thorulfr** [comment]
MUI and Tailwind seem pretty damn good to me.

**Comment by Thenlie** [comment]
@Thorulfr 
> MUI and Tailwind seem pretty damn good to me.

I am good with this. 

I am a little hesitant on tailwind as I think it might be preferable to have styling outside of the actual component file. For example, if we have a button that is styled the same in several places, that styling should all be controlled from a single spot. I don't think tailwind prevents this but I also don't think it encourages it. 

If we do go with tailwind we should look into creating groups of classes that can be applied all at once. Let me know if I can help!

**Comment by Thenlie** [comment]
✅ Tailwind
