### ISSUE TITLE
📝Create Supabase DB connection

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#46]
# Supabase!

- [x] Create supabase account
- [x] Create basic user schema on supabase
- [x] Connect to supabase in the app
- [x] Build sample login screen (no styling)
- [x] Route to sample dashboard screen on success?

## 🔗 Resources

https://supabase.com/docs/guides/with-react

**Comment by Thenlie** [comment]
@maxh1231 would you mind making a `.env.template` file to be included in the repo with the names of the vars? This should make it easier for new people to create an env.
