### ISSUE TITLE
✏️  Create add-to-favorites button

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#500]
## Create a button to add shows to a user's Favorites

The idea behind this column is for user's to add their favorite shows to their profile, which creates a more personable dashboard especially when it comes to user-user interactions. 

- Create button to add a show to favorites array
    - Conditionally display based on: [ login state, favorite state ]
- Create method to add/remove
- Integrate the two

**Comment by Thenlie** [comment]
This should for sure live on the show details page. It could also live on the show list card.

**Comment by Thenlie** [comment]
Closed by #529
