### ISSUE TITLE
🧼 Discover Screen Refactor

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#517]
The current screen is more or less un-styled component. We should create at least a basic implementation of the final screen. 

Some ideas to add are:

### Filters
- [x] Trending
- [x] Highest rated
- [x] Most liked
- [x] Newly added

### Genres
- [x] Action & Adventure
- [x] Horror
- [x] Comedy
- [ ] Documentary
- [ ] Sci-Fi

And more!

**Comment by Thenlie** [comment]
Closed by #639
