### ISSUE TITLE
🧼 Refactor text inputs to use a custom component

### ISSUE THREAD

**Issue by phillpeters** [Thenlie/Streamability#524]
The various forms throughout the app such as Login and Signup use multiple text fields to capture input. Currently each text field is added to its respective form as a combination of FormControl, InputLabel, and FilledInput MUI components, creating a lot of repetitive boilerplate. This boilerplate can be wrapped in a custom component. There may be a need for more than one custom component depending on how well the component can support different types of inputs such as email addresses and passwords.

## Resources
https://mui.com/material-ui/api/form-control/
https://mui.com/material-ui/api/input-label/
https://mui.com/material-ui/api/filled-input/

**Comment by Thenlie** [comment]
The components that contain one or more text inputs are:

- [ ] Login form
- [ ] Signup form
- [ ] Edit Profile modal
- [ ] Search Input (?)

**Comment by Thenlie** [comment]
Closed by #579
