### ISSUE TITLE
📝Create MovieDB connection and basic utility functions

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#53]
# Movie DB

Get an API ket for The Movie DB and set up some basic fetch requests. These can all be stored in a dedicated directory and exported to the rest of the app. 

If possible, unit test should also be made for these functions.

## 🔗 Resources

https://www.themoviedb.org/documentation/api?language=en-US

**Comment by maxh1231** [comment]
- [ ] Get a list a movies by name
- [ ] Get movie details by ID

**Comment by Thenlie** [comment]
Closed by #85
