### ISSUE TITLE
💡Determine data to display on user Dashboard

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#58]
Create tickets for queries and mutations that will need to be created for all the necessary data.

## 🔗 Resources

https://supabase.com/docs/guides/with-react

See "Account Page" section

```
const getProfile = async () => {
        try {
            setLoading(true)
            const { user } = session

            let { data, error, status } = await supabase
                .from('profiles')
                .select(`username`)
                .eq('id', user.id)
                .single()

            if (error && status !== 406) {
                throw error
            }

            if (data) {
                setUsername(data.username)
                setWebsite(data.website)
                setAvatarUrl(data.avatar_url)
            }
        } catch (error) {
            alert(error.message)
        } finally {
            setLoading(false)
        }
    }
```
This function will retrieve data from 'profiles' table, and set states for Username, Website, Avatar. This is a good starting template.

**Comment by Thenlie** [comment]
This ticket is going to pertain to user information such as username, account age, etc. Other tickets will be created for setting up the users watch queue, favorites, etc.

**Comment by Thenlie** [comment]
Created the following tickets to improve the initial user structure of the DB and connect it to the application. 

#52 
#79 
#80
