### ISSUE TITLE
✏️ Banner Component

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#618]
### Banner Component 

- Used in FeaturedSearchScreen, see [here](https://github.com/Thenlie/Streamability/blob/c4cbd70234095612663f63b5f3f40a81e1914f3b/src/screens/FeaturedSearchScreen.tsx#L14C5-L14C5)
- To be used in Discover Screen
- And more if needed

**Comment by Thenlie** [comment]
Closed by #619
