### ISSUE TITLE
✏️ Refactor ShowCarousel to handle loading data

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#624]
### `ShowCarousel` does not handle displaying loader components for its own data.

Currently, each location that `ShowCarousel` is called, has its own handling of rendering loaders. This functionality should be handled internally by the component itself. 

This would look like updating `ShowCarousel` component props to accept a boolean to display loader or carousel.

**Comment by Thenlie** [comment]
Closed by #629
