### ISSUE TITLE
🐞 Refreshing search results page removes profile buttons

### ISSUE THREAD

**Issue by maxh1231** [Thenlie/Streamability#655]
## Description 💬

Profile buttons no longer displayed after refreshing search results screen.

### Reproduction Steps 🪜

Steps to reproduce the unexpected behavior: (required)
1. Login
2. Search a TV Show or Movie
3. Refresh page
4. See buttons no longer displaying
5. This bug is not consistently repeatable. 

### Expected Behavior

Add to profile buttons persist on page

### Actual Behavior

Add to profile buttons no longer display

> NOTE: They will appear again if you update the display view

## Screenshots 📸

![image](https://github.com/Thenlie/Streamability/assets/41771785/3d715b04-b387-4857-8797-4771d1d53de6)

**Comment by Thenlie** [comment]
While we are looking at this, we should consider more generally how to avoid the profile from returning `null` before the profile has loaded when logged in. Ideally the first response we get back is the correct one, even if we need to wait a bit.

**Comment by Thenlie** [comment]
Closed by #682
