### ISSUE TITLE
📝🎨 Add basic darkmode switch

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#97]
Figure out a way to theme the application. This could use the device default theme and then be overridden in settings. It can be a simple light/dark or a full custom theme switcher/customizer. Feel free to spin off a bunch more issues to make this a big feature. 

For now, get something working so we can start to see how to design components/styling with theming in mind. We will likely want a color palette that can be swapped out in one place an impact the entire app.

**Comment by Thenlie** [comment]
A note worth mentioning... we currently only have a dark mode designed, so we should also design a light mode palette

**Comment by jadenrapp** [comment]
Closed by #138
