### ISSUE TITLE
📝Create ShowGallery screen

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/Streamability#99]
Create a screen will dozens of movies to just browse. These eventually will be able to be filtered by type, genre, provider, etc. 

We will want to think about efficient loading, maybe only rendering movie cards that are in the screen view.

**Comment by Thenlie** [comment]
Maybe add a new MovieDB request for trending or popular movies.

**Comment by maxh1231** [comment]
Component created. Add filters with #100
